<?php

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\webform\Entity\Webform;

/**
 * @file
 * Contains ik_d8_webform_extend.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ik_d8_webform_extend_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ik_d8_webform_extend module.
    case 'help.page.ik_d8_webform_extend':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extend the Webform module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter()
 */
function ik_d8_webform_extend_form_webform_settings_form_alter(&$form, FormStateInterface $form_state) {
  dpm($form);

  $webform = $form_state->getFormObject()->getEntity();

  $form['general_settings']['highlight'] = [
    '#type' => 'checkbox',
    '#title' => 'Highlight webform',
    '#description' => t('Show webform in list components'),
    '#default_value' => $webform->getThirdPartySetting('ik_d8_webform_extend', 'highlight')
  ];

  $form['#entity_builders'][] = 'ik_d8_webform_extend_form_webform_settings_form_builder';
}

function ik_d8_webform_extend_form_webform_settings_form_builder($entity_type, Webform $webform, &$form, FormStateInterface $form_state) {
  if ($form_state->getValue('highlight')) {
    $webform->setThirdPartySetting('ik_d8_webform_extend', 'highlight', $form_state->getValue('highlight'));
    return;
  }

  $webform->unsetThirdPartySetting('ik_d8_webform_extend', 'highlight');
}
